import * as Buttons from "./button/index.js";
import Card from "./card/index.js";
import * as Form from "./form/index.js";
import * as Tabs from "./tabs/index.js";
import Icon from "./icon.js";
import Loader from "./loader.js";
import ProgressBar from "./progress-bar.js";
import * as Type from "./type.js";
import WLoader from "./w-loader.js";
export {Buttons, Card, Form, Tabs, Icon, Loader, ProgressBar, Type, WLoader};
